version: '3'

services:
  bridge:
    build:
      context: ./docker
      dockerfile: ./server.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/ssl/
